app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, TextAreaField,SubmitField, SelectField,FileField)
from wtforms.validators import DataRequired
from flask_wtf.file import FileField, FileRequired, FileAllowed


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [DataRequired()])
    submit = SubmitField('Submit')

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    image_file = FileField( 'Picture',validators=[FileRequired()])
    content = TextAreaField('Description', validators=[DataRequired()])
    submit = SubmitField('Post')

class CommentForm(FlaskForm):
    comment = TextAreaField("Post Comment", validators=[DataRequired()])
    alias = StringField("Comment by")
    submit = SubmitField("Comment")

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from email.mime import image
from . import main
from flask import render_template,request,redirect,url_for,abort,flash
from ..models import  User,Comment,Post,Subscribers,Upvote
from .forms import UpdateProfile,PostForm,CommentForm
from .. import db,photos
from flask_login import login_required,current_user
from ..email import mail_message,welcome_message
from datetime import datetime






@main.route("/", methods = ["GET", "POST"])
def index():
    
    posts = Post.query.order_by(Post.date_posted.desc()).all()
    
    if request.method == "POST":
        new_sub = Subscribers(email = request.form.get("subscriber"))
        db.session.add(new_sub)
        db.session.commit()
        welcome_message("Thank you for subscribing to lynne blog", "email/welcome", new_sub.email)
    return render_template("main/index.html",posts = posts)

@main.route("/post/<int:id>", methods = ["POST", "GET"])
def post(id):
    post = Post.query.filter_by(id = id).first()
  
    
    comments = Comment.query.filter_by(post_id = id).all()
    comment_form = CommentForm()
    comment_count = len(comments)

    if comment_form.validate_on_submit():
        comment = comment_form.comment.data
        comment_form.comment.data = ""
        comment_alias = comment_form.alias.data
        comment_form.alias.data = ""
        if current_user.is_authenticated:
            comment_alias = current_user.username
        new_comment = Comment(comment = comment, comment_at = datetime.now(),comment_by = comment_alias,post_id = id)
        new_comment.save_comment()
        return redirect(url_for("main.post", id = post.id))

    return render_template("main/post.html", post = post,comments = comments,comment_form = comment_form,comment_count = comment_count)



@main.route("/post/new", methods = ["POST", "GET"])
@login_required
def new_post():
    subscribers = Subscribers.query.all()

    post_form = PostForm()
    if post_form.validate_on_submit():
        post_title = post_form.title.data
        post_form.title.data = ""

        filename = photos.save(post_form.image_file.data)
        path = f'photos/{filename}'


        post_content = post_form.content.data
        post_form.content.data = ""
        user_id = current_user._get_current_object().id

       

        new_post = Post(title = post_title, content = post_content,user_id=current_user._get_current_object().id,image_file=path)
        new_post.save_post()
        subs = Subscribers.query.all()
        for subscriber in subscribers:
            mail_message("New Blog Post","email/welcome_user",subscriber.email,new_post=new_post)
        return redirect(url_for("main.index", id = new_post.id))
    
    return render_template("main/new_post.html",post_form = post_form)




@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)    
@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)    

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))
    
@main.route('/comment/<int:blog_id>', methods = ['POST','GET'])
def comment(blog_id):
    form = CommentForm()
    post = Post.query.get(blog_id)
    all_comments = Comment.query.filter_by(blog_id = blog_id).all()
    if form.validate_on_submit():
        comment = form.comment.data
        blog_id = blog_id
        new_comment = Comment(comment = comment,blog_id = blog_id)
        new_comment.save_comment()
        return redirect(url_for('.comment', blog_id = blog_id))
    return render_template('main/comment.html', form =form,  post =  post,all_comments=all_comments)

@main.route('/subscribe',methods = ['POST','GET'])
def subscribe():
    email = request.form.get('subscriber')
    new_subscriber = Subscribers(email = email)
    new_subscriber.save_subscriber()
    mail_message("Subscribed to LinkSpace","email/welcome_user",new_subscriber.email,new_subscriber=new_subscriber)
    flash('Sucessfuly subscribed')
    return redirect(url_for('main.index'))


@main.route('/like/<int:id>', methods=['POST', 'GET'])
@login_required
def upvote(id):
    post = Post.query.get(id)
    vote_mpya = Upvote(post=post, upvote=1)
    vote_mpya.save()
    return redirect(url_for('main.index',id = post.id))

app/templates/main/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.css" rel="stylesheet" />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{url_for('static',filename='style.css')}}">
    <!-- Styles block -->

    <title>LinkSpace</title>
</head>

<body>
    {% extends 'bootstrap/base.html'%}

    {% include 'main/navbar.html' %}


    {% block content %}


    {% endblock %}


    <!-- MDB -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.js"></script>
    <!-- booostrap js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>


</body>

</html>

app/templates/main/errors.html
<h3>error page</h3>

app/templates/main/index.html
{% extends 'main/base.html'%}{% import 'main/macros.html' as macro %}

<!-- Styles block -->

{% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}" /> {% endblock %}

<!-- Content block -->



{% block content %}


<div class="container-fluid " id="bg-img" >



</div>
<div class="container">
    <div class="row" id="row">
        <h3 style="font-family: pacifico;font-weight: bolder;font-size: 45px;text-align: center;"><b>ABOUT US</b></h3>
        <div class="col-md-6" id="col2">

            <p>Feedback is a very powerful tool and is at the heart of effective design. Through Linkspace, find like-minded professionals to give you feedback on your designs. </p>
            <div class="btns">
                <a href="#about-header">
                    <a href="/post/new"><button class="btn btn-lg" style="background-color: darkcyan;">Join Us Today!</button></a>

                </a>




            </div>
        </div>
        <div class="col-md-6" id="col1">

            <img src="{{url_for('static', filename='images/aboutus1.png')}}" />

        </div>
    </div>
</div>
<!-- SERVICESS -->


<div class="container mt-5" id="servic">
    <div class="content">

        <div class="services text-center">

            <h3 style="font-family: pacifico;font-weight: bolder;font-size: 45px;text-align: center;"><b>PROJECT TYPES</b></h3>
            <p style="font-size: 18px;">Designs, illustrations, and graphic elements inspired by the world's best designers. View our Projects</p>
            <div class="border"></div>

        </div>
        <div class="row row-cols-1 row-cols-md-3 g-4 mt-5" id="card-content">
            <div class="col h-100" id="services">
                <div class="card" id="card-services">
                    <i class="fa fa-desktop" aria-hidden="true"></i>
                    <div class="card-body">
                        <h5 class="card-title">UX/UI Design</h5>
                        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                    </div>
                </div>
            </div>
            <div class="col" id="services">
                <div class="card" id="card-services">
                    <i class="fa fa-cogs" aria-hidden="true"></i>
                    <div class="card-body">
                        <h5 class="card-title">Web Development Desigs</h5>
                        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                    </div>
                </div>
            </div>
            <div class="col" id="services">
                <div class="card" id="card-services">
                    <i class="fa fa-mobile" aria-hidden="true"></i>
                    <div class="card-body">
                        <h5 class="card-title">Copywright Desing</h5>
                        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                    </div>
                </div>
            </div>
            <div class="col" id="services">
                <div class="card" id="card-services">
                    <i class="fa fa-rocket" aria-hidden="true"></i>
                    <div class="card-body">
                        <h5 class="card-title">Graghic Desing</h5>
                        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                    </div>
                </div>
            </div>
            <div class="col" id="services">
                <div class="card" id="card-services">
                    <i class="fa fa-camera" aria-hidden="true"></i>
                    <div class="card-body">
                        <h5 class="card-title">Photography</h5>
                        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                    </div>
                </div>
            </div>
            <div class="col" id="services">
                <div class="card" id="card-services">
                    <i class="fa fa-gamepad" aria-hidden="true"></i>
                    <div class="card-body">
                        <h5 class="card-title">Game Designs</h5>
                        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                    </div>
                </div>
            </div>
        </div>


    </div>

</div>

<!-- Projects -->
<div class="container">
    <div class="display">{{macro.display(posts)}}</div>

</div>
<!-- add projects here -->
<!-- team -->
<!-- subscribe -->
<div class="container" id="bg-cont">
    <div class="row">
        <h3 style="font-family: pacifico;font-weight: bolder;font-size: 45px;text-align: center;margin-top: 4%;"><b>SUBSCRIBE</b></h3>
        <div class="col-md-6" id="email">
            <h3>Subscribe to our Newsletter</h3>

            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
            <div class="sub">
                {% for message in get_flashed_messages() %}
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert">&times;</button> {{ message }}
                </div>
                {% endfor %}
                <form class="form-inline" action="{{url_for('main.subscribe')}}" method="POST">
                    <div class="md-form form-group" id="emails">
                        <label class="white-color">Email Address...</label>
                        <input type="email" class="form-control " name="subscriber" required>
                    </div>
                    <div class="md-form form-group">
                        <button class="btn btn-sm btn-outline-info" id="subs">Subscribe</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-6" id="for-img">
            <img src="{{url_for('static', filename='8.png')}}" />

        </div>
    </div>
</div>
</div>
    <!-- contact section -->
    <section class="contact" id="contacts">
        <div class="container" id="for-contact">
            <div class="contact-container">
                <h2>LINKSPACE</h2>
                <h4>Phone: +254748860959</h4>
                <h4>Email - linkspace@gmail.com</h4>
            </div>
            <div class="container-opening">
                <h2>Customer Help</h2>
                <h5>User Support</h5>
                <h5>FAQs</h5>
                <h5>Offers</h5>
            </div>
            <div class="container-opening">
                <h2>Useful Links</h2>
                <h5>Privacy Policy</h5>
                <h5>Join Us</h5>
                <h5>About</h5>
                <h5>Contact Us</h5>

            </div>
            <div class="container-opening">
                <h2>Connect With Us</h2>
                <div class="icons">
                    <i class="fa fa-pinterest" aria-hidden="true" style="color: red;"></i>
                    <i class="fa fa-instagram" aria-hidden="true" style="color: brown;"></i>
                    <i class="fa fa-linkedin" aria-hidden="true"></i>
                   <i class="fa fa-facebook" aria-hidden="true" style="color: blue;"></i>
                     <i class="fa fa-twitter" aria-hidden="true" style="color: rgb(7, 224, 248);"></i>
                </div>
               
                

            </div>
        </div>

    </section>
    <!-- Footer -->
    <footer class="page-footer text-white font-small blue">

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">© 2022 Copyright:LinkSpace
            <!-- <a href="https://mdbootstrap.com/"> MDBootstrap.com</a> -->
        </div>

    </footer>
{% endblock%}

app/templates/main/macros.html
{% macro display(posts) %}
<div class="container mt-5">
    <h1 class="" style="font-family: pacifico;font-weight: bolder;font-size: 45px;text-align: center;"><b>POSTS</b></h1>
    <a href="/post/new"><button class="btn" style="background-color: darkcyan;">New Post</button></a>
    <div class="row">
        {% if posts %} {% for post in posts %}

        <div class="col-md-4" id="cardss" style="margin-top: 1%;">
            <div class="card h-100" id="carded">
                <img src="{{url_for('static',filename=post.image_file)}}" class="card-img-top" alt="..." />
                <div class="card-body" id="textcard">
                    <h5 class="card-title">{{post.title}}</h5>
                    <p class="card-text">{{post.content}}</p>
                    <div>

                        <a href="/post/{{post.id}}"><button class="btn btn-info" style="background-color: darkcyan;"> {{post.comment.count()}}  Comments  </button></a>
                        <a href="/like/{{post.id}}"><button class="btn btn-success" style="background-color: darkcyan;"> {{post.up_vote.count()}}  Likes </button></a>
                        <h1>{{upvotes}}</h1>
                    </div>

                </div>

                <div class="card-footer" id="for-footer">
                    <small class="text-muted">Posted by: {{post.username}} Date posted: {{post.date_posted}}</small>
                </div>


            </div>
        </div>
        {% endfor%}{%endif%}
    </div>
</div>
{% endmacro %} {% macro display_comments(comments) %}
<div class="container">
</div>
<div class="card-columns">
    {% for comment in comments %}
    <div class="card">
        <div class="card-header">
        </div>
        <div class="card-body">
            <p>{{comment.comment}}</p>
        </div>
        <p class="text-center">{{comment.post_title}}</p>
    </div>
    {% endfor %}
</div>

{% endmacro %}

app/templates/main/navbar.html
<!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->
    <nav class="navbar navbar-expand-lg navbar-light ">

    <a class="navbar-brand" href="#" id="logo">LinkSpace</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse ms-auto" id="navbarNav">
        <ul class="navbar-nav">
          
            <li class="nav-item">
                <a class="nav-link"id="home" href="{{url_for('main.index')}}">Home</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" id="home" href="/post/new"> New Design<span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <div>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li id="auth"><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>

                <li class="auth">{{current_user.username}}</li>
                <li id="auth"><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li id="auth"><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
            </ul>
        </div>
    </div>
</nav>

app/templates/main/new_post.html
{% extends 'main/base.html'%} {% import 'bootstrap/wtf.html' as wtf %} {% block content %}

<body>

    <div class="container" style="background-image: url(/static/images/comment.jpeg);padding-bottom: 5%;">
        <div class="row col-md-12" style="margin-top: 6%;padding-top: 5%;padding-bottom: 5%;width: 50%;border-radius: 20px;margin-left: 25%;background-color: white;">
            <div class="col-md-2"></div>
            <div class="col-md-8">{{wtf.quick_form(post_form)}}</div>
            <div class="col-md-2"></div>
        </div>
    </div>


</body>


{% endblock%}

app/templates/main/post.html
{% extends 'main/base.html'%}{% import 'bootstrap/wtf.html' as wtf%}{% import 'main/macros.html' as macro %} {% from 'main/macros.html' import display%} {% from 'main/macros.html' import display_comments%}{% block content %}

<body>


    <div class="container" style="background-image: url(/static/images/comment.jpeg);padding-bottom: 5%;padding-top: 4%;">
        <div class="row" style="margin-top: 2%;">

            <div class="col-md-4">{{macro.display_comments(comments)}}</div>



        </div>
        <div class="row col-md-12" style="margin-top: 2%;padding-top: 5%;padding-bottom: 5%;width: 50%;border-radius: 20px;margin-left: 25%;background-color: white;">
            <div class="col-md-2"></div>
            <div class="col-md-8">{{wtf.quick_form(comment_form)}}</div>
            <div class="col-md-2"></div>
        </div>

    </div>



    {% endblock %}